### ISSUE TITLE
Support for Customizing StorageClass

### ISSUE THREAD

**Issue by anaik91** [apigee/ansible-apigee-hybrid-accelerator#19]
**Is your feature request related to a problem? Please describe.**
Add support for customizing StorageClass for Cassandra PVCs

**Describe the solution you'd like**
Adding Support  StorageClass to support all platforms

**Describe alternatives you've considered**
NA
**Additional context**
NA

**Comment by RiflerRick** [comment]
@anaik91 
Given the following requiremnts:
- Ability for users to define the storage class name, provisioner and parameters in the vars file, the storage class should be crated by the playbook
- Provide validation to make sure users cannot change the storage class if a cassandra statefulset already exists in the environment. 
- Validate the storage class provided by the user against the actual underlying k8s platform. 

With regard to the 3rd requirement, can we converge on a set of platforms we want to support? There does not seem to be a standard way to identify the underlying provider of the k8s platform. For example with node-labels we can potentially identify the platform as GKE or AWS, however there does not seem to be a standard around this. Let me know your thoughts on this

**Comment by anaik91** [comment]
@RiflerRick : how about supporting for the platform mentioned here : https://cloud.google.com/apigee/docs/hybrid/supported-platforms
